const LOGIN_SUCCESS = 'auth.LOGIN_SUCCESS';

const LOGOUT_SUCCESS = 'auth.LOGOUT_SUCCESS';

const VERIFY_REQUEST = 'auth.VERIFY_REQUEST';
const VERIFY_SUCCESS = 'auth.VERIFY_SUCCESS';

export { LOGIN_SUCCESS, LOGOUT_SUCCESS, VERIFY_REQUEST, VERIFY_SUCCESS };
