const CREATE_LEAGUE_SUCCESS = 'leagues.CREATE_LEAGUE_SUCCESS';
const INITIALIZE_LEAGUE = 'leagues.INITIALIZE_LEAGUE';
const INITIALIZE_LEAGUES = 'leagues.INITIALIZE_LEAGUES';

export { CREATE_LEAGUE_SUCCESS, INITIALIZE_LEAGUE, INITIALIZE_LEAGUES };
